version: '3.3'

services:
  apache:
    build:
      context: ./apache
    ports:
      - 8080:80
    networks:
      - frontend
      - backend
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./www:/usr/local/apache2/htdocs
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./php
    volumes:
      - ./www:/usr/local/apache2/htdocs
    restart: always
    networks:
      - backend

  mysql:
    build: ./mysql
    restart: always
    networks:
      - backend
    volumes:
      - ./database:/var/lib/mysql
networks: 
  backend:
  frontend:


